### ISSUE TITLE
Encrypt string hangs for ever

### ISSUE THREAD

**Issue by jagan999** [brianPlummer/AndroidEncryptionExample#9]
Hi,
I tried using your example but it gets hung on the encryption itself. Any recommendations?
Jagan

**Comment by brianPlummer** [comment]
hey there @jagan999 I'm not sure why it's not working.  There are log statements in the catch blocks throughout the call chain.  If you could see if there is a stack trace in the log it could lead to the issue.  let me know what you find and if i can help you out in any way.

**Comment by brianPlummer** [comment]
Any luck @jagan999 ??
